topics:
- name: /twist_marker_server/cmd_vel
  type: geometry_msgs/Twist
  fields:
  - name: linear
    data_type: geometry_msgs/Vector3
  - name: linear.x
    data_type: float64
  - name: linear.y
    data_type: float64
  - name: linear.z
    data_type: float64
  - name: angular
    data_type: geometry_msgs/Vector3
  - name: angular.x
    data_type: float64
  - name: angular.y
    data_type: float64
  - name: angular.z
    data_type: float64
  publishers:
  - /twist_marker_server
  subscribers:
  - /twist_mux
- name: /tf
  type: tf2_msgs/TFMessage
  fields:
  - name: transforms
    data_type: geometry_msgs/TransformStamped[]
  - name: transforms.header
    data_type: std_msgs/Header
  - name: transforms.header.seq
    data_type: uint32
  - name: transforms.header.stamp
    data_type: time
  - name: transforms.header.frame_id
    data_type: string
  - name: transforms.child_frame_id
    data_type: string
  - name: transforms.transform
    data_type: geometry_msgs/Transform
  - name: transforms.transform.translation
    data_type: geometry_msgs/Vector3
  - name: transforms.transform.translation.x
    data_type: float64
  - name: transforms.transform.translation.y
    data_type: float64
  - name: transforms.transform.translation.z
    data_type: float64
  - name: transforms.transform.rotation
    data_type: geometry_msgs/Quaternion
  - name: transforms.transform.rotation.x
    data_type: float64
  - name: transforms.transform.rotation.y
    data_type: float64
  - name: transforms.transform.rotation.z
    data_type: float64
  - name: transforms.transform.rotation.w
    data_type: float64
  publishers:
  - /ekf_localization
  - /robot_state_publisher
  - /gazebo
  subscribers:
  - /ekf_localization
- name: /tf_static
  type: tf2_msgs/TFMessage
  fields:
  - name: transforms
    data_type: geometry_msgs/TransformStamped[]
  - name: transforms.header
    data_type: std_msgs/Header
  - name: transforms.header.seq
    data_type: uint32
  - name: transforms.header.stamp
    data_type: time
  - name: transforms.header.frame_id
    data_type: string
  - name: transforms.child_frame_id
    data_type: string
  - name: transforms.transform
    data_type: geometry_msgs/Transform
  - name: transforms.transform.translation
    data_type: geometry_msgs/Vector3
  - name: transforms.transform.translation.x
    data_type: float64
  - name: transforms.transform.translation.y
    data_type: float64
  - name: transforms.transform.translation.z
    data_type: float64
  - name: transforms.transform.rotation
    data_type: geometry_msgs/Quaternion
  - name: transforms.transform.rotation.x
    data_type: float64
  - name: transforms.transform.rotation.y
    data_type: float64
  - name: transforms.transform.rotation.z
    data_type: float64
  - name: transforms.transform.rotation.w
    data_type: float64
  publishers:
  - /robot_state_publisher
  subscribers:
  - /ekf_localization
- name: /joy_teleop/cmd_vel
  type: geometry_msgs/Twist
  fields:
  - name: linear
    data_type: geometry_msgs/Vector3
  - name: linear.x
    data_type: float64
  - name: linear.y
    data_type: float64
  - name: linear.z
    data_type: float64
  - name: angular
    data_type: geometry_msgs/Vector3
  - name: angular.x
    data_type: float64
  - name: angular.y
    data_type: float64
  - name: angular.z
    data_type: float64
  publishers:
  - /joy_teleop/teleop_twist_joy
  subscribers:
  - /twist_mux
- name: /joy_teleop/joy
  type: sensor_msgs/Joy
  fields:
  - name: header
    data_type: std_msgs/Header
  - name: header.seq
    data_type: uint32
  - name: header.stamp
    data_type: time
  - name: header.frame_id
    data_type: string
  - name: axes
    data_type: float32[]
  - name: buttons
    data_type: int32[]
  publishers:
  - /joy_teleop/joy_node
  subscribers:
  - /joy_teleop/teleop_twist_joy
- name: /husky_velocity_controller/cmd_vel
  type: geometry_msgs/Twist
  fields:
  - name: linear
    data_type: geometry_msgs/Vector3
  - name: linear.x
    data_type: float64
  - name: linear.y
    data_type: float64
  - name: linear.z
    data_type: float64
  - name: angular
    data_type: geometry_msgs/Vector3
  - name: angular.x
    data_type: float64
  - name: angular.y
    data_type: float64
  - name: angular.z
    data_type: float64
  publishers:
  - /twist_mux
  subscribers:
  - /gazebo
- name: /odometry/filtered
  type: nav_msgs/Odometry
  fields:
  - name: header
    data_type: std_msgs/Header
  - name: header.seq
    data_type: uint32
  - name: header.stamp
    data_type: time
  - name: header.frame_id
    data_type: string
  - name: child_frame_id
    data_type: string
  - name: pose
    data_type: geometry_msgs/PoseWithCovariance
  - name: pose.pose
    data_type: geometry_msgs/Pose
  - name: pose.pose.position
    data_type: geometry_msgs/Point
  - name: pose.pose.x
    data_type: float64
  - name: pose.pose.y
    data_type: float64
  - name: pose.pose.z
    data_type: float64
  - name: pose.pose.orientation
    data_type: geometry_msgs/Quaternion
  - name: pose.pose.orientation.x
    data_type: float64
  - name: pose.pose.orientation.y
    data_type: float64
  - name: pose.pose.orientation.z
    data_type: float64
  - name: pose.pose.orientation.w
    data_type: float64
  - name: pose.covariance
    data_type: float64[36]
  - name: twist
    data_type: geometry_msgs/TwistWithCovariance
  - name: twist.twist
    data_type: geometry_msgs/Twist
  - name: twist.twist.linear
    data_type: geometry_msgs/Vector3
  - name: twist.twist.linear.x
    data_type: float64
  - name: twist.twist.linear.y
    data_type: float64
  - name: twist.twist.linear.z
    data_type: float64
  - name: twist.twist.angular
    data_type: geometry_msgs/Vector3
  - name: twist.twist.angular.x
    data_type: float64
  - name: twist.twist.angular.y
    data_type: float64
  - name: twist.twist.angular.z
    data_type: float64
  - name: twist.covariance
    data_type: float64[36]
  publishers:
  - /ekf_localization
  subscribers: []
